// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function jsonEnd(res, payload) {
  var json = Belt_Option.getExn(JSON.stringify(payload));
  var jsonLen = json.length;
  res.setHeader("Content-Type", "application/json").setHeader("Content-Length", jsonLen).end(json);
}

export {
  jsonEnd ,
}
/* No side effect */
