// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");

function jsonEnd(res, payload) {
  res.end(Belt_Option.getExn(JSON.stringify(payload)));
}

exports.jsonEnd = jsonEnd;
/* No side effect */
